### ISSUE TITLE
document the load balancing tool

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/user-guide#6]
https://www.rc.colorado.edu/node/507

I think this could probably be included in the batch queueing and job scheduling page; but the current documentation doesn't make me comfortable enough to document it further. I need to work with someone who's used it before, or look at the source code.

I also can't get it to run, as it keeps complaining about a missing shared library from opensm. It might require something that's only present on a compute node. (I've been trying to run --help from the login node.)

**Comment by tbrown-curc** [comment]
Done: examples-and-tutorials/load-balancer.html
